import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: 'Lebensmittel Temperaturprüfer', eyebrow: 'THERMOMETER CHECK', subtitle: 'Verwandle einen Messwert in den nächsten klaren Schritt für dein Essen.',
  foodLabel: 'Lebensmittelkategorie', temperatureLabel: 'Gemessene Kerntemperatur', unitCelsius: 'Celsius (°C)', unitFahrenheit: 'Fahrenheit (°F)', resultTitle: 'Dein Messwert', measuredLabel: 'Gemessen', targetLabel: 'Mindestziel', differenceLabel: 'Differenz',
  statusBelow: 'Unter dem Minimum', statusMeets: 'Minimum erreicht', statusAbove: 'Über dem Minimum', belowDescription: 'Weitergaren oder an einer anderen Stelle messen. Der Wert hat das dokumentierte Minimum noch nicht erreicht.', meetsDescription: 'Das dokumentierte Minimum ist erreicht. Beachte den Ruhehinweis und die Regeln für den sicheren Umgang mit Lebensmitteln.', aboveDescription: 'Der Messwert liegt über dem dokumentierten Minimum. Sicherheit und persönlicher Gargrad sind getrennte Entscheidungen.', restLabel: 'Ruhezeit nach dem Ziel', noRestNeeded: 'Keine Ruhezeit angegeben', sourceLabel: 'Quelle', sourceName: 'FoodSafety.gov-Tabelle', placementTip: 'An der dicksten Stelle messen, Knochen und Kontakt mit Pfanne vermeiden und ein kalibriertes Thermometer verwenden.', noteTitle: 'Sicherheitsgrenze', noteText: 'Dieser Prüfer vergleicht nur Temperaturen. Lagerung, Umgang, Thermometergenauigkeit und jedes lebensmittelspezifische Risiko können nicht geprüft werden.',
  poultryOption: 'Geflügel und Füllung', groundMeatOption: 'Hackfleisch und Wurst', redMeatCutsOption: 'Rind, Bison, Kalb, Ziege und Lamm: Steaks, Braten, Koteletts', porkCutsOption: 'Schwein: Steaks, Braten und Koteletts', rawHamOption: 'Roher Schinken', precookedHamOption: 'Vorgegarter Schinken (Aufwärmen)', rabbitVenisonOption: 'Kaninchen und Wild', fishOption: 'Fisch', eggDishesOption: 'Eierspeisen', casserolesOption: 'Aufläufe', leftoversOption: 'Reste und aufgewärmte Speisen',
  poultryNote: 'Mindestens 74 °C / 165 °F für Geflügel und Füllung.', groundMeatNote: 'Mindestens 71 °C / 160 °F für Hackfleisch und Wurst.', redMeatCutsNote: 'Mindestens 63 °C / 145 °F, danach 3 Minuten ruhen lassen.', porkCutsNote: 'Mindestens 63 °C / 145 °F, danach Schweinefleisch 3 Minuten ruhen lassen.', rawHamNote: 'Mindestens 63 °C / 145 °F, danach rohen Schinken 3 Minuten ruhen lassen.', precookedHamNote: 'Vorgegarten Schinken auf mindestens 74 °C / 165 °F erhitzen.', rabbitVenisonNote: 'Mindestens 71 °C / 160 °F für Kaninchen und Wild.', fishNote: 'Mindestens 63 °C / 145 °F für ganze Fische und Filets.', eggDishesNote: 'Mindestens 71 °C / 160 °F für Eierspeisen wie Quiche oder Frittata.', casserolesNote: 'Mindestens 74 °C / 165 °F für Aufläufe mit oder ohne Fleisch.', leftoversNote: 'Reste auf mindestens 74 °C / 165 °F erhitzen.',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = {
  title: ui.title, description: 'Prüfe eine gemessene Lebensmitteltemperatur gegen dokumentierte sichere Mindestkerntemperaturen. Wechsle sofort zwischen Celsius und Fahrenheit und erfahre, ob du weitergaren, ruhen lassen oder nachmessen solltest.', ui, faqTitle: 'Fragen zur Lebensmitteltemperatur',
  faq: [
    { question: 'Was zeigt dieser Lebensmittel-Temperaturprüfer?', answer: 'Er vergleicht deinen Thermometerwert mit der dokumentierten sicheren Mindestkerntemperatur der gewählten Kategorie und zeigt Untergrenze, erreichtes Minimum oder einen höheren Wert sowie Differenz und Ruhezeit.' },
    { question: 'Ist das Erreichen des Ziels eine vollständige Sicherheitsgarantie?', answer: 'Nein. Die Mindestwerte gelten für korrekt behandelte Lebensmittel. Lagerfehler, Kreuzkontamination, ein ungenaues Thermometer und andere Risiken werden dadurch nicht ausgeschlossen.' },
    { question: 'Wo setze ich das Thermometer ein?', answer: 'Setze die Spitze in die dickste Stelle und vermeide Knochen, Fett, Knorpel, Pfanne und Garfläche. Bei dünnen Lebensmitteln von der Seite bis zur Mitte einstechen.' },
    { question: 'Warum brauchen manche Lebensmittel eine Ruhezeit?', answer: 'Bei bestimmten ganzen Fleischstücken gehört die dreiminütige Ruhezeit zur offiziellen Empfehlung und muss nach dem Herausnehmen aus der Hitze eingehalten werden.' },
  ],
  howTo: [
    { name: 'Lebensmittelkategorie wählen', text: 'Wähle die Kategorie, die zu deinem Lebensmittel passt. Das dokumentierte Mindestziel ist lokal im Prüfer hinterlegt.' },
    { name: 'Thermometerwert eingeben', text: 'Gib die Temperatur aus der dicksten Stelle ein und wähle Celsius oder Fahrenheit passend zu deinem Thermometer.' },
    { name: 'Entscheidung lesen', text: 'Unter dem Ziel bedeutet weitergaren oder nachmessen. Erreicht bedeutet Minimum erreicht. Darüber liegt über dem Minimum, während der persönliche Gargrad separat bleibt.' },
    { name: 'Ruhehinweis beachten', text: 'Wenn eine Ruhezeit angegeben ist, halte sie vor dem Anschneiden oder Essen ein und befolge weiterhin die Hinweise zu Lagerung und Hygiene.' },
  ],
  seoCopy: { uiBadge: 'Wichtig', readTitle: 'Lebensmittelthermometer richtig ablesen', readText: 'Ein Lebensmittelthermometer beantwortet eine enge, aber wichtige Frage: Hat die Mitte des Lebensmittels die dokumentierte sichere Mindestkerntemperatur erreicht? Wähle eine Kategorie, gib den Messwert ein und vergleiche beide Werte direkt im Browser.', donenessTitle: 'Mindesttemperatur ist nicht dasselbe wie Gargrad', donenessText: 'Ein Mindestziel ist eine Sicherheitsreferenz, keine Zusage für Textur oder persönliche Vorlieben. Der Prüfer bewertet die Sicherheitsgrenze, nicht dein gewünschtes Ergebnis im Teller.', tableHeaders: ['Lebensmittelkategorie', 'Mindesttemperatur', 'Ruhehinweis'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3 Minuten'], [ui.porkCutsOption, '63 °C / 145 °F', '3 Minuten'], [ui.rawHamOption, '63 °C / 145 °F', '3 Minuten'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: 'Die Mitte messen, nicht die Oberfläche', measureText: 'Führe die Spitze in die dickste Stelle ein und vermeide Knochen, Fett, Knorpel, Pfanne und Garfläche. Bei dünnen Lebensmitteln seitlich bis zur Mitte messen.', limitsTitle: 'Ein Temperaturcheck hat Grenzen', limitsText: 'Eine Mindesttemperatur korrigiert keine unsichere Lagerung, Kreuzkontamination oder ein ungenaues Thermometer. Befolge die vollständigen Hinweise der Quellen.', offlineTitle: 'Warum der Prüfer offline funktioniert', offlineText: 'Kategorien und Mindestwerte sind als kleine versionierte Datensammlung gebündelt. Umrechnung, Vergleich, Status, Differenz und Ruhehinweis laufen ohne API oder Live-Daten im Browser.' },
};

export const content = createFoodSafetyContent(copy, 'de');
