import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: 'Comprobador de temperatura segura', eyebrow: 'CONTROL DEL TERMÓMETRO', subtitle: 'Convierte una lectura en el siguiente paso claro para la comida que tienes delante.',
  foodLabel: 'Categoría de alimento', temperatureLabel: 'Temperatura interna medida', unitCelsius: 'Celsius (°C)', unitFahrenheit: 'Fahrenheit (°F)', resultTitle: 'Tu lectura', measuredLabel: 'Medida', targetLabel: 'Mínimo objetivo', differenceLabel: 'Diferencia',
  statusBelow: 'Por debajo del mínimo', statusMeets: 'Mínimo alcanzado', statusAbove: 'Por encima del mínimo', belowDescription: 'Sigue cocinando o mide en otro punto. La lectura todavía no ha alcanzado el mínimo documentado para esta categoría.', meetsDescription: 'La lectura ha alcanzado el mínimo documentado. Aplica el tiempo de reposo indicado y continúa siguiendo las pautas de manipulación segura.', aboveDescription: 'La lectura está por encima del mínimo documentado. La seguridad y el punto de cocción que prefieras son decisiones distintas.', restLabel: 'Reposo tras alcanzar el objetivo', noRestNeeded: 'Sin reposo indicado', sourceLabel: 'Fuente', sourceName: 'Tabla de FoodSafety.gov', placementTip: 'Mide la parte más gruesa, evita el hueso y el contacto con la bandeja, y utiliza un termómetro calibrado.', noteTitle: 'Límite de seguridad', noteText: 'Este comprobador solo compara temperaturas. No puede verificar la conservación, la manipulación, la precisión del termómetro ni todos los riesgos específicos de cada alimento.',
  poultryOption: 'Aves y relleno', groundMeatOption: 'Carne picada y salchichas', redMeatCutsOption: 'Cortes de ternera, bisonte, ternera, cabra y cordero', porkCutsOption: 'Filetes, asados y chuletas de cerdo', rawHamOption: 'Jamón crudo', precookedHamOption: 'Jamón precocinado (recalentar)', rabbitVenisonOption: 'Conejo y venado', fishOption: 'Pescado', eggDishesOption: 'Platos con huevo', casserolesOption: 'Cazuelas y gratinados', leftoversOption: 'Sobras y comida recalentada',
  poultryNote: 'Mínimo: 74 °C / 165 °F para aves y relleno.', groundMeatNote: 'Mínimo: 71 °C / 160 °F para carne picada y salchichas.', redMeatCutsNote: 'Mínimo: 63 °C / 145 °F, seguido de 3 minutos de reposo.', porkCutsNote: 'Mínimo: 63 °C / 145 °F, seguido de 3 minutos de reposo para el cerdo.', rawHamNote: 'Mínimo: 63 °C / 145 °F, seguido de 3 minutos de reposo para el jamón crudo.', precookedHamNote: 'Recalienta el jamón precocinado hasta un mínimo de 74 °C / 165 °F.', rabbitVenisonNote: 'Mínimo: 71 °C / 160 °F para conejo y venado.', fishNote: 'Mínimo: 63 °C / 145 °F para pescado entero y filetes.', eggDishesNote: 'Mínimo: 71 °C / 160 °F para platos con huevo como quiche o frittata.', casserolesNote: 'Mínimo: 74 °C / 165 °F para cazuelas con o sin carne.', leftoversNote: 'Recalienta las sobras hasta un mínimo de 74 °C / 165 °F.',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = {
  title: ui.title, description: 'Compara una temperatura interna medida con mínimos documentados de cocción segura. Cambia entre Celsius y Fahrenheit al instante y descubre si necesitas seguir cocinando, dejar reposar o volver a medir.', ui, faqTitle: 'Preguntas sobre temperatura y seguridad alimentaria',
  faq: [
    { question: '¿Qué me dice este comprobador de temperatura?', answer: 'Compara la lectura de tu termómetro con el mínimo interno documentado para la categoría elegida y devuelve si está por debajo, ha alcanzado el mínimo o está por encima, junto con la diferencia y el reposo indicado.' },
    { question: '¿Alcanzar el objetivo garantiza completamente la seguridad?', answer: 'No. Son mínimos para alimentos manipulados correctamente. No sustituyen una conservación segura ni corrigen contaminación cruzada, un termómetro impreciso u otros riesgos específicos.' },
    { question: '¿Dónde debo colocar el termómetro?', answer: 'Introduce la sonda en la parte más gruesa y evita hueso, grasa, cartílago, bandeja y superficie de cocción. En alimentos finos, introdúcela de lado hasta el centro.' },
    { question: '¿Por qué algunos alimentos necesitan reposo?', answer: 'En ciertos cortes enteros, los tres minutos de reposo forman parte de la recomendación oficial y deben respetarse después de retirar la carne del calor.' },
  ],
  howTo: [
    { name: 'Elige la categoría', text: 'Selecciona la categoría que mejor describa lo que estás cocinando. El mínimo documentado está incluido localmente en el comprobador.' },
    { name: 'Introduce la lectura', text: 'Escribe la temperatura medida en la parte más gruesa y elige Celsius o Fahrenheit según tu termómetro.' },
    { name: 'Lee la decisión', text: 'Por debajo significa seguir cocinando o comprobar de nuevo. Alcanzado significa que has llegado al mínimo. Por encima supera el mínimo, pero no define tus preferencias de cocción.' },
    { name: 'Aplica el reposo', text: 'Si la categoría indica un tiempo de reposo, respétalo antes de cortar o comer y sigue las indicaciones completas de manipulación y conservación.' },
  ],
  seoCopy: { uiBadge: 'Importante', readTitle: 'Cómo leer un termómetro de cocina', readText: 'Un termómetro de cocina responde a una pregunta concreta: ¿el centro del alimento ha alcanzado la temperatura interna mínima documentada? Elige una categoría, introduce tu lectura y compara ambos valores directamente en el navegador.', donenessTitle: 'La temperatura mínima no es lo mismo que el punto de cocción', donenessText: 'El mínimo es una referencia de seguridad, no una promesa de textura o gusto personal. El comprobador evalúa el umbral de seguridad, no si el resultado te parece más o menos hecho.', tableHeaders: ['Categoría', 'Temperatura mínima', 'Reposo'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3 minutos'], [ui.porkCutsOption, '63 °C / 145 °F', '3 minutos'], [ui.rawHamOption, '63 °C / 145 °F', '3 minutos'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: 'Mide el centro, no la superficie', measureText: 'Introduce la sonda en la parte más gruesa y evita hueso, grasa, cartílago, bandeja y superficie de cocción. En alimentos finos, mide desde el lateral hasta el centro.', limitsTitle: 'El control de temperatura tiene límites', limitsText: 'Alcanzar el mínimo no corrige una conservación insegura, la contaminación cruzada o un termómetro impreciso. Sigue las instrucciones completas de las fuentes.', offlineTitle: 'Por qué funciona sin conexión', offlineText: 'Las categorías y mínimos forman una pequeña dataset versionada incluida en la herramienta. La conversión, comparación, estado, diferencia y reposo funcionan en el navegador sin API ni datos en directo.' },
};

export const content = createFoodSafetyContent(copy, 'es');
