import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: 'Vérificateur de température des aliments', eyebrow: 'CONTRÔLE DU THERMOMÈTRE', subtitle: 'Transformez une mesure en prochaine étape claire pour l\'aliment sur votre planche.',
  foodLabel: 'Catégorie d\'aliment', temperatureLabel: 'Température à cœur mesurée', unitCelsius: 'Celsius (°C)', unitFahrenheit: 'Fahrenheit (°F)', resultTitle: 'Votre mesure', measuredLabel: 'Mesure', targetLabel: 'Minimum visé', differenceLabel: 'Écart',
  statusBelow: 'Sous le minimum', statusMeets: 'Minimum atteint', statusAbove: 'Au-dessus du minimum', belowDescription: 'Poursuivez la cuisson ou mesurez un autre endroit. La mesure n\'atteint pas encore le minimum documenté.', meetsDescription: 'La mesure atteint le minimum documenté. Respectez le temps de repos indiqué et les règles de manipulation sûre.', aboveDescription: 'La mesure dépasse le minimum documenté. La sécurité et le degré de cuisson préféré sont deux décisions différentes.', restLabel: 'Repos après le seuil', noRestNeeded: 'Aucun repos indiqué', sourceLabel: 'Source', sourceName: 'Tableau FoodSafety.gov', placementTip: 'Mesurez la partie la plus épaisse, évitez l\'os et le contact avec le plat, et utilisez un thermomètre étalonné.', noteTitle: 'Limite de sécurité', noteText: 'Cet outil compare uniquement la température. Il ne vérifie ni la conservation, ni la manipulation, ni la précision du thermomètre, ni tous les risques propres à chaque aliment.',
  poultryOption: 'Volaille et farce', groundMeatOption: 'Viande hachée et saucisses', redMeatCutsOption: 'Bœuf, bison, veau, chèvre et agneau en morceaux', porkCutsOption: 'Porc: steaks, rôtis et côtelettes', rawHamOption: 'Jambon cru', precookedHamOption: 'Jambon précuit (réchauffage)', rabbitVenisonOption: 'Lapin et venaison', fishOption: 'Poisson', eggDishesOption: 'Plats aux œufs', casserolesOption: 'Gratins et plats en cocotte', leftoversOption: 'Restes et plats réchauffés',
  poultryNote: 'Minimum: 74 °C / 165 °F pour toute volaille et farce.', groundMeatNote: 'Minimum: 71 °C / 160 °F pour la viande hachée et les saucisses.', redMeatCutsNote: 'Minimum: 63 °C / 145 °F, puis 3 minutes de repos.', porkCutsNote: 'Minimum: 63 °C / 145 °F, puis 3 minutes de repos pour le porc.', rawHamNote: 'Minimum: 63 °C / 145 °F, puis 3 minutes de repos pour le jambon cru.', precookedHamNote: 'Réchauffez le jambon précuit à au moins 74 °C / 165 °F.', rabbitVenisonNote: 'Minimum: 71 °C / 160 °F pour le lapin et la venaison.', fishNote: 'Minimum: 63 °C / 145 °F pour les filets et poissons entiers.', eggDishesNote: 'Minimum: 71 °C / 160 °F pour les plats aux œufs, comme la quiche ou la frittata.', casserolesNote: 'Minimum: 74 °C / 165 °F pour les gratins avec ou sans viande.', leftoversNote: 'Réchauffez les restes à au moins 74 °C / 165 °F.',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = {
  title: ui.title, description: 'Comparez une température mesurée avec les températures internes minimales documentées pour une cuisson sûre. Passez instantanément des Celsius aux Fahrenheit et voyez s\'il faut poursuivre, laisser reposer ou mesurer à nouveau.', ui, faqTitle: 'Questions sur la température des aliments',
  faq: [
    { question: 'Que m\'indique ce vérificateur de température ?', answer: 'Il compare votre mesure au minimum interne documenté de la catégorie choisie et indique si elle est inférieure, atteint le minimum ou le dépasse, avec l\'écart et le temps de repos éventuel.' },
    { question: 'Atteindre la cible garantit-il totalement la sécurité ?', answer: 'Non. Ces minima supposent une manipulation correcte. Ils ne corrigent pas une mauvaise conservation, une contamination croisée, un thermomètre imprécis ou un autre risque particulier.' },
    { question: 'Où placer la sonde du thermomètre ?', answer: 'Placez-la dans la partie la plus épaisse en évitant l\'os, le gras, le cartilage, le plat et la surface de cuisson. Pour les aliments fins, insérez-la par le côté jusqu\'au centre.' },
    { question: 'Pourquoi certains aliments demandent-ils un repos ?', answer: 'Pour certains morceaux entiers, les trois minutes de repos font partie de la recommandation officielle après le retrait de la source de chaleur.' },
  ],
  howTo: [
    { name: 'Choisir la catégorie', text: 'Sélectionnez la catégorie qui correspond le mieux à votre aliment. Le minimum documenté est intégré localement dans l\'outil.' },
    { name: 'Saisir la mesure', text: 'Entrez la température prise dans la partie la plus épaisse et choisissez Celsius ou Fahrenheit selon votre thermomètre.' },
    { name: 'Lire la décision', text: 'Sous le seuil signifie poursuivre ou vérifier à nouveau. Seuil atteint signifie que le minimum est atteint. Au-dessus dépasse le minimum, sans définir la cuisson que vous préférez.' },
    { name: 'Respecter le repos', text: 'Si la catégorie indique un repos, respectez-le avant de découper ou de manger et suivez les recommandations complètes de manipulation.' },
  ],
  seoCopy: { uiBadge: 'Important', readTitle: 'Lire un thermomètre de cuisine', readText: 'Un thermomètre de cuisine répond à une question précise: le centre de l\'aliment a-t-il atteint la température interne minimale documentée ? Choisissez une catégorie, saisissez la mesure et comparez les deux valeurs dans le navigateur.', donenessTitle: 'La température minimale n\'est pas le degré de cuisson', donenessText: 'Le minimum est une référence de sécurité, pas une promesse de texture ou de préférence. L\'outil évalue le seuil de sécurité, pas le résultat sensoriel souhaité.', tableHeaders: ['Catégorie', 'Température minimale', 'Repos'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3 minutes'], [ui.porkCutsOption, '63 °C / 145 °F', '3 minutes'], [ui.rawHamOption, '63 °C / 145 °F', '3 minutes'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: 'Mesurer le centre, pas la surface', measureText: 'Insérez la sonde dans la partie la plus épaisse et évitez l\'os, le gras, le cartilage, le plat et la surface de cuisson. Pour les aliments fins, mesurez depuis le côté jusqu\'au centre.', limitsTitle: 'Un contrôle de température a ses limites', limitsText: 'Atteindre un minimum ne corrige ni une conservation dangereuse, ni une contamination croisée, ni un thermomètre imprécis. Consultez les recommandations complètes des sources.', offlineTitle: 'Pourquoi l\'outil fonctionne hors ligne', offlineText: 'Les catégories et minima sont réunis dans un petit jeu de données versionné. Conversion, comparaison, statut, écart et repos fonctionnent dans le navigateur sans API ni données en direct.' },
};

export const content = createFoodSafetyContent(copy, 'fr');
