import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: '食品安全温度チェッカー', eyebrow: '温度計チェック', subtitle: '測定値を、目の前の料理に必要な次の行動へ変換します。', foodLabel: '食品カテゴリー', temperatureLabel: '測定した中心温度', unitCelsius: '摂氏 (°C)', unitFahrenheit: '華氏 (°F)', resultTitle: '測定結果', measuredLabel: '測定値', targetLabel: '最低目標温度', differenceLabel: '差分', statusBelow: '最低温度未満', statusMeets: '最低温度に到達', statusAbove: '最低温度超過', belowDescription: '加熱を続けるか、別の場所を測定してください。このカテゴリーの記録された最低温度に達していません。', meetsDescription: '記録された最低温度に達しました。休ませる時間が示されている場合は守り、安全な取り扱いを続けてください。', aboveDescription: '記録された最低温度を超えています。安全性と好みの火の通り具合は別の判断です。', restLabel: '目標到達後の休ませ時間', noRestNeeded: '休ませる時間の記載なし', sourceLabel: '出典', sourceName: 'FoodSafety.gov の表', placementTip: '最も厚い部分を測り、骨や調理容器に触れないようにし、校正済みの温度計を使ってください。', noteTitle: '安全性の範囲', noteText: 'このチェッカーが比較するのは温度だけです。保存状態、取り扱い、温度計の精度、食品ごとのすべてのリスクは確認できません。', poultryOption: '家禽類と詰め物', groundMeatOption: 'ひき肉とソーセージ', redMeatCutsOption: '牛肉、バイソン、仔牛、ヤギ、羊のステーキ・ロースト・チョップ', porkCutsOption: '豚肉のステーキ・ロースト・チョップ', rawHamOption: '生ハム', precookedHamOption: '加熱済みハム（再加熱）', rabbitVenisonOption: 'ウサギと鹿肉', fishOption: '魚', eggDishesOption: '卵料理', casserolesOption: 'キャセロール', leftoversOption: '残り物・再加熱する料理', poultryNote: '家禽類と詰め物は最低 74°C / 165°F。', groundMeatNote: 'ひき肉とソーセージは最低 71°C / 160°F。', redMeatCutsNote: '最低 63°C / 145°F。加熱後3分間休ませます。', porkCutsNote: '豚肉は最低 63°C / 145°F。加熱後3分間休ませます。', rawHamNote: '生ハムは最低 63°C / 145°F。加熱後3分間休ませます。', precookedHamNote: '加熱済みハムは最低 74°C / 165°F まで再加熱します。', rabbitVenisonNote: 'ウサギと鹿肉は最低 71°C / 160°F。', fishNote: '魚の切り身と丸魚は最低 63°C / 145°F。', eggDishesNote: 'キッシュやフリッタータなどの卵料理は最低 71°C / 160°F。', casserolesNote: '肉入り・肉なしのキャセロールは最低 74°C / 165°F。', leftoversNote: '残り物は最低 74°C / 165°F まで再加熱します。',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = { title: ui.title, description: '測定した食品の温度を、記録された安全な最低中心温度と比較します。摂氏と華氏をすぐに切り替え、加熱を続けるか、休ませるか、測り直すかを判断できます。', ui, faqTitle: '食品温度についての質問', faq: [{ question: 'この食品温度チェッカーで何が分かりますか？', answer: '選択したカテゴリーの記録された最低中心温度と温度計の値を比較し、最低温度未満・到達・超過を差分と休ませる時間とともに表示します。' }, { question: '目標温度に達すれば安全が完全に保証されますか？', answer: 'いいえ。これは食品が適切に扱われていることを前提にした最低温度です。不適切な保存、交差汚染、温度計の誤差などは解決しません。' }, { question: '温度計はどこに差し込みますか？', answer: '最も厚い部分に差し込み、骨、脂肪、軟骨、調理容器、加熱面を避けます。薄い食品は側面から中心へ差し込みます。' }, { question: 'なぜ休ませる食品があるのですか？', answer: '一部の大きな肉の塊では、火から下ろした後の3分間の休ませ時間が公式な推奨事項に含まれています。' }], howTo: [{ name: '食品カテゴリーを選ぶ', text: '調理している食品に最も合うカテゴリーを選びます。記録された最低温度はチェッカーにローカルで収録されています。' }, { name: '温度計の値を入力する', text: '最も厚い部分で測った温度を入力し、温度計に合わせて摂氏または華氏を選びます。' }, { name: '判断結果を読む', text: '最低温度未満なら加熱または再測定が必要です。到達なら最低温度に達しています。超過は安全の最低値を上回る状態で、好みの火の通り具合とは別です。' }, { name: '休ませ時間を適用する', text: 'カテゴリーに休ませ時間がある場合は、切り分けたり食べたりする前に守り、保存と衛生の指示も続けてください。' }], seoCopy: { uiBadge: '重要', readTitle: '食品温度計の読み方', readText: '食品温度計は、食品の中心が記録された安全な最低中心温度に達したかという具体的な問いに答えます。カテゴリーを選び、測定値を入力して、ブラウザー内で比較します。', donenessTitle: '最低温度と好みの火の通り具合は別です', donenessText: '最低温度は安全性の基準であり、食感や好みを保証するものではありません。このチェッカーは安全の境界を確認します。', tableHeaders: ['食品カテゴリー', '最低温度', '休ませ時間'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3分'], [ui.porkCutsOption, '63 °C / 145 °F', '3分'], [ui.rawHamOption, '63 °C / 145 °F', '3分'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: '表面ではなく中心を測る', measureText: '最も厚い部分にプローブを差し込み、骨、脂肪、軟骨、容器、加熱面を避けます。薄い食品は側面から中心へ測ります。', limitsTitle: '温度チェックには限界があります', limitsText: '最低温度に達しても、不適切な保存、交差汚染、温度計の誤差は解決しません。出典の完全な取り扱い指示に従ってください。', offlineTitle: 'オフラインで動作する理由', offlineText: 'カテゴリーと最低温度は小さなバージョン管理済みデータセットとして内蔵されています。変換、比較、状態、差分、休ませ時間はAPIやライブデータなしでブラウザー内で動作します。' } };

export const content = createFoodSafetyContent(copy, 'ja');
