import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: '식품 안전 온도 확인기', eyebrow: '온도계 확인', subtitle: '측정값을 지금 요리 중인 음식에 필요한 다음 행동으로 바꿔 줍니다.', foodLabel: '식품 분류', temperatureLabel: '측정한 중심 온도', unitCelsius: '섭씨 (°C)', unitFahrenheit: '화씨 (°F)', resultTitle: '측정 결과', measuredLabel: '측정값', targetLabel: '최저 목표', differenceLabel: '차이', statusBelow: '최저 온도 미만', statusMeets: '최저 온도 도달', statusAbove: '최저 온도 초과', belowDescription: '조리를 계속하거나 다른 지점을 측정하세요. 이 분류의 문서화된 최저 온도에 아직 도달하지 않았습니다.', meetsDescription: '문서화된 최저 온도에 도달했습니다. 휴지 시간이 표시되어 있다면 적용하고 안전한 식품 취급 지침을 계속 따르세요.', aboveDescription: '문서화된 최저 온도를 넘었습니다. 안전성과 개인적인 익힘 정도는 별개의 판단입니다.', restLabel: '목표 도달 후 휴지', noRestNeeded: '휴지 시간 없음', sourceLabel: '출처', sourceName: 'FoodSafety.gov 표', placementTip: '가장 두꺼운 부분을 측정하고 뼈와 팬에 닿지 않게 하며 보정된 온도계를 사용하세요.', noteTitle: '안전 범위', noteText: '이 확인기는 온도만 비교합니다. 보관, 취급, 온도계 정확도 또는 식품별 모든 위험을 확인할 수 없습니다.', poultryOption: '가금류와 속재료', groundMeatOption: '간 고기와 소시지', redMeatCutsOption: '소고기·들소·송아지·염소·양고기 스테이크·로스트·찹', porkCutsOption: '돼지고기 스테이크·로스트·찹', rawHamOption: '생햄', precookedHamOption: '가열 조리된 햄(재가열)', rabbitVenisonOption: '토끼고기와 사슴고기', fishOption: '생선', eggDishesOption: '달걀 요리', casserolesOption: '캐서롤', leftoversOption: '남은 음식과 재가열 음식', poultryNote: '가금류와 속재료는 최소 74°C / 165°F입니다.', groundMeatNote: '간 고기와 소시지는 최소 71°C / 160°F입니다.', redMeatCutsNote: '최소 63°C / 145°F에 도달한 뒤 3분간 휴지합니다.', porkCutsNote: '돼지고기는 최소 63°C / 145°F에 도달한 뒤 3분간 휴지합니다.', rawHamNote: '생햄은 최소 63°C / 145°F에 도달한 뒤 3분간 휴지합니다.', precookedHamNote: '가열 조리된 햄은 최소 74°C / 165°F까지 재가열합니다.', rabbitVenisonNote: '토끼고기와 사슴고기는 최소 71°C / 160°F입니다.', fishNote: '생선 전체와 필레는 최소 63°C / 145°F입니다.', eggDishesNote: '키시나 프리타타 같은 달걀 요리는 최소 71°C / 160°F입니다.', casserolesNote: '고기가 들어간 캐서롤과 고기가 없는 캐서롤은 최소 74°C / 165°F입니다.', leftoversNote: '남은 음식은 최소 74°C / 165°F까지 재가열합니다.',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = { title: ui.title, description: '측정한 식품 온도를 문서화된 안전 최저 중심 온도와 비교합니다. 섭씨와 화씨를 즉시 전환하고 계속 조리할지, 휴지할지, 다시 측정할지 확인하세요.', ui, faqTitle: '식품 온도 관련 질문', faq: [{ question: '이 식품 온도 확인기는 무엇을 알려 주나요?', answer: '선택한 식품 분류의 문서화된 최저 중심 온도와 온도계 측정값을 비교해 미만, 도달 또는 초과 상태와 차이 및 휴지 시간을 보여 줍니다.' }, { question: '목표 온도에 도달하면 안전이 완전히 보장되나요?', answer: '아니요. 이 최저값은 식품을 올바르게 취급했다는 전제에서 사용합니다. 잘못된 보관, 교차 오염, 부정확한 온도계 등은 해결하지 않습니다.' }, { question: '온도계는 어디에 꽂아야 하나요?', answer: '가장 두꺼운 부분에 꽂고 뼈, 지방, 연골, 팬과 조리면을 피하세요. 얇은 음식은 옆에서 중심까지 꽂습니다.' }, { question: '왜 어떤 음식에는 휴지 시간이 필요한가요?', answer: '일부 고기 덩어리는 열원에서 내린 뒤 3분간 휴지하는 것이 공식 권고에 포함됩니다.' }], howTo: [{ name: '식품 분류 선택', text: '요리 중인 음식에 가장 잘 맞는 분류를 선택하세요. 문서화된 최저값은 확인기에 로컬로 포함되어 있습니다.' }, { name: '온도계 측정값 입력', text: '가장 두꺼운 부분에서 측정한 온도를 입력하고 온도계에 맞춰 섭씨 또는 화씨를 선택하세요.' }, { name: '판정 읽기', text: '미만이면 더 조리하거나 다시 확인해야 합니다. 도달이면 최저값에 도달한 것입니다. 초과는 최저값보다 높다는 뜻이며 개인 취향의 익힘 정도와는 다릅니다.' }, { name: '휴지 시간 적용', text: '분류에 휴지 시간이 있다면 자르거나 먹기 전에 지키고 보관과 위생 지침도 계속 따르세요.' }], seoCopy: { uiBadge: '중요', readTitle: '식품 온도계 읽는 법', readText: '식품 온도계는 음식 중심이 문서화된 안전 최저 중심 온도에 도달했는지 확인합니다. 분류를 고르고 측정값을 입력하면 브라우저에서 두 값을 비교합니다.', donenessTitle: '최저 온도와 익힘 정도는 다릅니다', donenessText: '최저값은 안전 기준이지 식감이나 개인 취향을 보장하는 값이 아닙니다. 이 도구는 안전 경계를 확인할 뿐 원하는 식감을 판정하지 않습니다.', tableHeaders: ['식품 분류', '최저 온도', '휴지 시간'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3분'], [ui.porkCutsOption, '63 °C / 145 °F', '3분'], [ui.rawHamOption, '63 °C / 145 °F', '3분'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: '표면이 아니라 중심을 측정하세요', measureText: '가장 두꺼운 부분에 탐침을 넣고 뼈, 지방, 연골, 팬과 조리면을 피하세요. 얇은 음식은 옆에서 중심으로 측정합니다.', limitsTitle: '온도 확인에는 한계가 있습니다', limitsText: '최저 온도에 도달해도 안전하지 않은 보관, 교차 오염 또는 부정확한 온도계를 해결하지 못합니다. 출처의 전체 지침을 따르세요.', offlineTitle: '오프라인으로 작동하는 이유', offlineText: '분류와 최저값은 작은 버전 관리 데이터셋으로 내장되어 있습니다. 변환, 비교, 상태, 차이와 휴지는 API나 실시간 데이터 없이 브라우저에서 실행됩니다.' } };

export const content = createFoodSafetyContent(copy, 'ko');
