import type { FoodSafetyLocaleCopy } from './create-content';
import { createFoodSafetyContent } from './create-content';

const ui = {
  title: '食品安全温度检查器', eyebrow: '温度计检查', subtitle: '把测量结果转换成处理眼前食物的明确下一步。', foodLabel: '食物类别', temperatureLabel: '测得的中心温度', unitCelsius: '摄氏度 (°C)', unitFahrenheit: '华氏度 (°F)', resultTitle: '测量结果', measuredLabel: '测得温度', targetLabel: '最低目标', differenceLabel: '差值', statusBelow: '低于最低温度', statusMeets: '已达到最低温度', statusAbove: '高于最低温度', belowDescription: '继续烹饪或测量其他位置。读数还没有达到该类别记录的最低温度。', meetsDescription: '读数已达到记录的最低温度。如有静置时间，请遵守并继续按照安全处理指南操作。', aboveDescription: '读数高于记录的最低温度。安全性和个人喜欢的熟度是两个不同的判断。', restLabel: '达到目标后的静置', noRestNeeded: '未注明静置时间', sourceLabel: '来源', sourceName: 'FoodSafety.gov 表格', placementTip: '测量最厚的部分，避开骨头和容器接触，并使用经过校准的温度计。', noteTitle: '安全边界', noteText: '本工具只比较温度，无法检查储存、处理方式、温度计准确度或所有食物特有的风险。', poultryOption: '家禽和填料', groundMeatOption: '绞肉和香肠', redMeatCutsOption: '牛肉、野牛肉、小牛肉、山羊肉和羊肉块', porkCutsOption: '猪排、猪肉烤肉和猪肉片', rawHamOption: '生火腿', precookedHamOption: '熟火腿（重新加热）', rabbitVenisonOption: '兔肉和鹿肉', fishOption: '鱼', eggDishesOption: '蛋类菜肴', casserolesOption: '焗烤菜和砂锅菜', leftoversOption: '剩菜和重新加热的食物', poultryNote: '家禽和填料最低 74°C / 165°F。', groundMeatNote: '绞肉和香肠最低 71°C / 160°F。', redMeatCutsNote: '最低 63°C / 145°F，然后静置 3 分钟。', porkCutsNote: '猪肉最低 63°C / 145°F，然后静置 3 分钟。', rawHamNote: '生火腿最低 63°C / 145°F，然后静置 3 分钟。', precookedHamNote: '将熟火腿重新加热至至少 74°C / 165°F。', rabbitVenisonNote: '兔肉和鹿肉最低 71°C / 160°F。', fishNote: '整鱼和鱼片最低 63°C / 145°F。', eggDishesNote: '乳蛋饼或意式煎蛋等蛋类菜肴最低 71°C / 160°F。', casserolesNote: '含肉或不含肉的焗烤菜最低 74°C / 165°F。', leftoversNote: '将剩菜重新加热至至少 74°C / 165°F。',
} satisfies Record<string, string>;

const copy: FoodSafetyLocaleCopy = { title: ui.title, description: '将测得的食物温度与记录中的安全最低中心温度进行比较。即时切换摄氏度和华氏度，判断是否需要继续烹饪、静置或重新测量。', ui, faqTitle: '关于食物温度的问题', faq: [{ question: '这个食物温度检查器能告诉我什么？', answer: '它会把温度计读数与所选类别的记录最低中心温度进行比较，并显示低于、达到或高于最低值的结果、差值和静置时间。' }, { question: '达到目标温度就能完全保证安全吗？', answer: '不能。这些最低值以正确处理食物为前提，无法纠正不安全的储存、交叉污染、温度计不准确或其他食物特有的风险。' }, { question: '食物温度计应该放在哪里？', answer: '将探针放在最厚的部分，避开骨头、脂肪、软骨、容器和加热表面。较薄的食物应从侧面插入中心。' }, { question: '为什么有些食物需要静置？', answer: '对于某些整块肉，离开热源后的三分钟静置属于官方建议的一部分。' }], howTo: [{ name: '选择食物类别', text: '选择最符合当前食物的类别。记录中的最低温度已本地包含在检查器中。' }, { name: '输入温度计读数', text: '输入最厚处测得的温度，并根据温度计选择摄氏度或华氏度。' }, { name: '读取判断结果', text: '低于目标表示继续烹饪或再次检查。达到目标表示已达到最低值。高于目标表示超过最低值，但不代表个人偏好的熟度。' }, { name: '应用静置时间', text: '如果类别标有静置时间，请在切开或食用前遵守，并继续遵循储存和卫生指南。' }], seoCopy: { uiBadge: '重要', readTitle: '如何读取食物温度计', readText: '食物温度计回答一个具体问题：食物中心是否达到记录中的安全最低中心温度？选择类别，输入读数，然后在浏览器中比较数值。', donenessTitle: '最低温度不等于熟度', donenessText: '最低温度是安全参考，不是对口感或个人偏好的保证。检查器评估的是安全边界，而不是你想要的口感。', tableHeaders: ['食物类别', '最低温度', '静置'], tableRows: [[ui.poultryOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.groundMeatOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.redMeatCutsOption, '63 °C / 145 °F', '3 分钟'], [ui.porkCutsOption, '63 °C / 145 °F', '3 分钟'], [ui.rawHamOption, '63 °C / 145 °F', '3 分钟'], [ui.precookedHamOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.rabbitVenisonOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.fishOption, '63 °C / 145 °F', ui.noRestNeeded], [ui.eggDishesOption, '71 °C / 160 °F', ui.noRestNeeded], [ui.casserolesOption, '74 °C / 165 °F', ui.noRestNeeded], [ui.leftoversOption, '74 °C / 165 °F', ui.noRestNeeded]], measureTitle: '测量中心而不是表面', measureText: '将探针插入最厚处，避开骨头、脂肪、软骨、容器和加热表面。较薄的食物应从侧面测量到中心。', limitsTitle: '温度检查有其局限', limitsText: '达到最低温度不能纠正不安全的储存、交叉污染或温度计不准确。请遵循来源提供的完整指南。', offlineTitle: '为什么检查器可以离线工作', offlineText: '类别和最低值作为小型版本化数据集内置。换算、比较、状态、差值和静置时间都在浏览器中运行，无需 API 或实时数据。' } };

export const content = createFoodSafetyContent(copy, 'zh');
